# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:              Hawaii Engineers
logo:               # Logo image URL
email:              kagawaa@gmail.com
description:        Hawaii's engineers. To help show the students of Hawaii that they can be engineers! 
baseurl:            '/hawaiiengineers' # The subpath of your site, e.g. /blog
url:                'https://kagawaa.github.io' # The base hostname & protocol for your site
github_username:    kagawaa
twitter_username:   kagawaa
instagram_username: kagawaa

markdown:  kramdown
permalink: pretty
paginate:  13
sass:
  style: compressed

gems:
  - jekyll-paginate
  - jekyll/tagging

include:
  - _pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

# Authors
authors:
  kagawaa:
    name:             Aaron Kagawa
    bio:              Software Engineer 
    gravatar:         https://secure.gravatar.com/avatar/4016c53f94c5ccc9f7fa58b8b26cb6ef
    email:            kagawaa@gmail.com
    website:          https://www.linkedin.com/in/aaronkagawa
    github_username:  kagawaa
    twitter_username: kagawaa
